from typing import *
from transformers import AutoModelForMultipleChoice

def generate_logits(model, inputs, labels):
	"""
	Pass your inputs and labels to the model and return the logits:

	Args:
		model (AutoModelForMultipleChoice): The pre-trained model for multiple choice tasks.
		inputs (dict): The inputs for the model.
		labels (torch.Tensor): The labels for the multiple choice task.

	Returns:
		torch.Tensor: The logits generated by the model.
	"""
	outputs = model(**{k: v.unsqueeze(0) for k, v in inputs.items()}, labels=labels)
	logits = outputs.logits
	return logits
